Transform: AWS::Serverless-2016-10-31

Resources:
  LayerCollection:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/collection

  ParameterLayerArnCollection:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: /ProjectArtemisLibrary/Layer/Collection
      Value: !Ref LayerCollection

Outputs:
  ParameterNameLayerArnCollection:
    Value: !Ref ParameterLayerArnCollection
